FROM ubuntu:22.04
RUN apt-get update -qq && \
    apt-get install -y -qq curl ca-certificates iproute2 iputils-ping dnsutils && \
    curl -fsSL https://get.docker.com | sh && \
    rm -rf /var/lib/apt/lists/*
