#!/usr/bin/env bash
# Phase M08 — Gloo Mesh management plane.
#
# Why this exists: Solo Enterprise for Istio (which M03 installs) gives the
# Istio mesh + east/west wire. But the *cross-cluster service publication*
# primitives — solo.io/service-scope=global, VirtualDestination, Workspace,
# etc. — come from Gloo Mesh, which is a separate helm chart layered on top.
#
# Topology (per the plan): Gloo Mesh management server is co-located in
# cluster-bank. Edge and vendor each run a gloo-mesh-agent that relays
# back to bank via a NodePort (kind has no LoadBalancers).

set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
export REPO_ROOT
source "$SCRIPT_DIR/../lib/config.sh"
source "$SCRIPT_DIR/../lib/common.sh"
source "$SCRIPT_DIR/../lib/topology.sh"
trap on_error ERR

[[ "$MODE" == "multi" ]] || die "08-gloo-mesh.sh requires MODE=multi"

GLOO_VERSION="${GLOO_PLATFORM_VERSION:-2.12.3}"
# Assume the same Solo license is valid for Gloo Mesh; override via env if not.
GLOO_LIC="${GLOO_MESH_LICENSE_KEY:-${SOLO_ISTIO_LICENSE_KEY:-}}"
[[ -n "$GLOO_LIC" ]] || die "GLOO_MESH_LICENSE_KEY (or SOLO_ISTIO_LICENSE_KEY) not set"

MGMT_RELAY_NODEPORT=31443

log_step "M08.1 — add gloo-platform helm repo"
helm repo add gloo-platform https://storage.googleapis.com/gloo-platform/helm-charts >/dev/null 2>&1 || true
helm repo update gloo-platform >/dev/null

# ---------- Management cluster (bank) ----------

log_step "M08.2 — gloo-mesh CRDs on $BANK_CLUSTER"
helm --kube-context="$(cluster_context "$BANK_CLUSTER")" upgrade --install \
  gloo-platform-crds gloo-platform/gloo-platform-crds \
  --namespace gloo-mesh --create-namespace \
  --version "$GLOO_VERSION" \
  --wait --timeout 5m >/dev/null

log_step "M08.3 — gloo-platform mgmt server on $BANK_CLUSTER"
# Override mgmt-server.yaml profile bits: (a) cluster name, (b) NodePort for
# the relay listener so edge+vendor agents can reach it via kind docker IPs,
# (c) license, (d) Workspace API enabled so we can use VirtualDestination.
cat > /tmp/gloo-mgmt-values.yaml <<EOF
common:
  cluster: $BANK_CLUSTER
glooMgmtServer:
  enabled: true
  serviceType: NodePort
  ports:
    grpc: 9900
  service:
    type: NodePort
    ports:
      - name: grpc
        port: 9900
        nodePort: $MGMT_RELAY_NODEPORT
        protocol: TCP
glooUi:
  enabled: true
prometheus:
  enabled: true
redis:
  deployment:
    enabled: true
telemetryCollector:
  enabled: true
telemetryGateway:
  enabled: true
glooInsightsEngine:
  enabled: true
EOF

helm --kube-context="$(cluster_context "$BANK_CLUSTER")" upgrade --install \
  gloo-platform gloo-platform/gloo-platform \
  --namespace gloo-mesh \
  --version "$GLOO_VERSION" \
  -f /tmp/gloo-mgmt-values.yaml \
  --set licensing.glooMeshLicenseKey="$GLOO_LIC" \
  --wait --timeout 10m

log "verifying mgmt-server pods"
kctx "$BANK_CLUSTER" -n gloo-mesh get pods --no-headers \
  | awk '{printf "    %-50s %s %s\n", $1, $2, $3}'

# ---------- Register each workload cluster with the mgmt server ----------
# Without these KubernetesCluster CRDs in the mgmt cluster's gloo-mesh ns,
# every agent gets PermissionDenied: "cluster <name> is not registered".
# Each cluster (including bank itself, which runs both mgmt and an agent)
# needs a matching CRD; the agent presents its clusterID via the relay and
# the mgmt server checks it against this list.

log_step "M08.4a — register clusters in mgmt server"
for cluster in "${CLUSTERS[@]}"; do
  kctx "$BANK_CLUSTER" apply -f - <<EOF >/dev/null
apiVersion: admin.gloo.solo.io/v2
kind: KubernetesCluster
metadata:
  name: $cluster
  namespace: gloo-mesh
spec:
  clusterDomain: cluster.local
EOF
  log "  registered $cluster"
done

# ---------- Trust bootstrap: copy relay secrets to workload clusters ----------

log_step "M08.4 — copy relay secrets from $BANK_CLUSTER to workload clusters"
# These two secrets are generated by the mgmt install. Agents need them to
# establish initial TLS + identity.
for sec in relay-root-tls-secret relay-identity-token-secret; do
  log "  copying $sec"
  kctx "$BANK_CLUSTER" -n gloo-mesh get secret "$sec" -o yaml \
    | sed '/resourceVersion:/d; /uid:/d; /creationTimestamp:/d; /namespace:/d' \
    > /tmp/$sec.yaml
  for cluster in "$EDGE_CLUSTER" "$VENDOR_CLUSTER"; do
    kctx "$cluster" create ns gloo-mesh --dry-run=client -o yaml | kctx "$cluster" apply -f - >/dev/null
    kctx "$cluster" -n gloo-mesh apply -f /tmp/$sec.yaml >/dev/null
  done
done

# ---------- Agents on workload clusters ----------

# Deterministic discovery of bank's relay address. Do NOT use docker inspect
# - kind can reshuffle the docker network IPs across restarts, and at one
# point this picked up the kind-registry container's IP (172.22.0.9) instead
# of a bank node, leaving every agent stuck in connection-refused.
#
# Pull a real worker InternalIP from the bank cluster itself. Workers (not
# the control-plane) are what the kubelet advertises for NodePort traffic,
# and the value is always current with whatever Docker/kind has on the host.
BANK_IP="$(kctx "$BANK_CLUSTER" get nodes \
  -l '!node-role.kubernetes.io/control-plane' \
  -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')"
[[ -n "$BANK_IP" ]] || die "could not discover bank worker InternalIP"

# The helm chart's service.ports[].nodePort override silently fails — the
# chart picks a random NodePort. Read the actual one out of the live Service
# so the agents get a working address.
ACTUAL_NP="$(kctx "$BANK_CLUSTER" -n gloo-mesh get svc gloo-mesh-mgmt-server -o jsonpath='{.spec.ports[?(@.name=="grpc")].nodePort}')"
[[ -n "$ACTUAL_NP" ]] || die "could not discover mgmt-server grpc NodePort"
RELAY_ADDR="${BANK_IP}:${ACTUAL_NP}"
log "agent relay address: $RELAY_ADDR  (bank worker InternalIP from k8s; NodePort discovered, requested $MGMT_RELAY_NODEPORT got $ACTUAL_NP)"

write_agent_values() {
  local cluster="$1" file="$2"
  # telemetryCollector disabled on workload-cluster agents — the gloo-platform
  # chart's collector requires an explicit otlp endpoint on workload clusters
  # and we already have a per-cluster otel-collector (M06) doing trace/log
  # forwarding. Re-enable later when wiring per-cluster OTel ship.
  cat > "$file" <<EOF
common:
  cluster: $cluster
glooAgent:
  enabled: true
  relay:
    serverAddress: $RELAY_ADDR
    authority: gloo-mesh-mgmt-server.gloo-mesh
telemetryCollector:
  enabled: false
# glooAnalyzer also tries to reach gloo-telemetry-collector; disable it on
# workload-cluster agents until the cross-cluster telemetry wiring is done.
glooAnalyzer:
  enabled: false
EOF
}

for cluster in "$EDGE_CLUSTER" "$VENDOR_CLUSTER" "$BANK_CLUSTER"; do
  log_step "M08.5 — gloo-mesh CRDs + agent on $cluster"
  if [[ "$cluster" != "$BANK_CLUSTER" ]]; then
    helm --kube-context="$(cluster_context "$cluster")" upgrade --install \
      gloo-platform-crds gloo-platform/gloo-platform-crds \
      --namespace gloo-mesh --create-namespace \
      --version "$GLOO_VERSION" \
      --set installIstioOperator=false \
      --wait --timeout 5m >/dev/null
  fi

  write_agent_values "$cluster" /tmp/gloo-agent-$cluster.yaml
  helm --kube-context="$(cluster_context "$cluster")" upgrade --install \
    gloo-platform-agent gloo-platform/gloo-platform \
    --namespace gloo-mesh \
    --version "$GLOO_VERSION" \
    -f /tmp/gloo-agent-$cluster.yaml \
    --set licensing.glooMeshLicenseKey="$GLOO_LIC" \
    --wait --timeout 10m >/dev/null
done

# ---------- Verify ----------

log_step "M08.6 — verify all agents connected to mgmt server"
sleep 10
for cluster in "${CLUSTERS[@]}"; do
  echo "  $cluster gloo-mesh pods:"
  kctx "$cluster" -n gloo-mesh get pods --no-headers \
    | awk '{printf "    %-50s %s %s\n", $1, $2, $3}'
done

log "registered KubernetesClusters at mgmt server:"
kctx "$BANK_CLUSTER" get kubernetescluster -A --no-headers 2>&1 \
  | awk '{printf "    %s/%s\n", $1, $2}' || true

log_ok "Phase M08 (Gloo Mesh) complete"
log "  next: M09 — apply solo.io/service-scope=global, define Workspaces, validate cross-cluster routing"
